export const starterTemplates = {
  python: `class Solution:\n    def solve(self, nums, target):\n        # Write your solution here\n        pass`,
  javascript: `var solve = function(nums, target) {\n    // Write your solution here\n};`,
  java: `class Solution {\n    public int[] solve(int[] nums, int target) {\n        // Write here\n        return new int[0];\n    }\n}`,
  cpp: `class Solution {\npublic:\n    vector<int> solve(vector<int>& nums, int target) {\n        // Write here\n        return {};\n    }\n};`,
  c: `#include <stdio.h>\n#include <stdlib.h>\n\nint* solve(int* nums, int numsSize, int target, int* returnSize) {\n    // Write here\n    *returnSize = 0;\n    return NULL;\n}`,
  go: `package main\n\nfunc solve(nums []int, target int) []int {\n    // Write here\n    return nil\n}`,
  rust: `fn solve(nums: Vec<i32>, target: i32) -> Vec<i32> {\n    // Write here\n    vec![]\n}`,
  kotlin: `class Solution {\n    fun solve(nums: IntArray, target: Int): IntArray {\n        // Write here\n        return intArrayOf()\n    }\n}`,
  typescript: `function solve(nums: number[], target: number): number[] {\n    // Write here\n    return [];\n}`,
  csharp: `public class Solution {\n    public int[] Solve(int[] nums, int target) {\n        // Write here\n        return new int[0];\n    }\n}`,
  swift: `class Solution {\n    func solve(_ nums: [Int], _ target: Int) -> [Int] {\n        // Write here\n        return []\n    }\n}`,
  ruby: `def solve(nums, target)\n    # Write here\nend`,
  php: `class Solution {\n    function solve($nums, $target) {\n        // Write here\n        return [];\n    }\n}`,
  scala: `object Solution {\n    def solve(nums: Array[Int], target: Int): Array[Int] = {\n        // Write here\n        Array()\n    }\n}`,
  perl: `sub solve {\n    my ($nums, $target) = @_;\n    # Write here\n    return ();\n}`,
  r: `solve <- function(nums, target) {\n  # Write here\n  return(c())\n}`,
  dart: `List<int> solve(List<int> nums, int target) {\n  // Write here\n  return [];\n}`,
  bash: `#!/bin/bash\n# Write here\n`,
  sql: `-- Write your SQL query here\nSELECT * FROM solutions;`,
  haskell: `solve :: [Int] -> Int -> [Int]\nsolve nums target = \n    -- Write here\n    []`,
  lua: `function solve(nums, target)\n    -- Write here\nend`,
  fsharp: `let solve (nums: int[]) (target: int) : int[] = \n    // Write here\n    [||]`,
  clojure: `(defn solve [nums target]\n  ;; Write here\n  [])`,
  elixir: `defmodule Solution do\n  def solve(nums, target) do\n    # Write here\n  end\nend`,
  erlang: `-module(solution).\n-export([solve/2]).\n\nsolve(Nums, Target) ->\n  %% Write here\n  [].`,
  groovy: `class Solution {\n    def solve(nums, target) {\n        // Write here\n    }\n}`,
  pascal: `program Solution;\nbegin\n  // Write here\nend.`,
  fortran: `program solution\n  ! Write here\nend program solution`,
  cobol: `IDENTIFICATION DIVISION.\nPROGRAM-ID. SOLUTION.\nPROCEDURE DIVISION.\n    *> Write here\n    STOP RUN.`,
  vbnet: `Module Solution\n    Sub Main()\n        ' Write here\n    End Sub\nEnd Module`,
  ocaml: `let solve nums target = \n  (* Write here *)\n  []`,
  prolog: `solve(Nums, Target, Result) :-\n    % Write here\n    fail.`,
  assembly: `; Write your assembly code here`,
};

export const MONACO_LANGUAGE_MAP = {
  python:     'python',
  javascript: 'javascript',
  typescript: 'typescript',
  java:       'java',
  cpp:        'cpp',
  c:          'c',
  csharp:     'csharp',
  go:         'go',
  rust:       'rust',
  kotlin:     'kotlin',
  swift:      'swift',
  ruby:       'ruby',
  php:        'php',
  scala:      'scala',
  perl:       'perl',
  r:          'r',
  dart:       'dart',
  bash:       'shell',
  sql:        'sql',
  haskell:    'haskell',
  lua:        'lua',
  fsharp:     'fsharp',
  clojure:    'clojure',
  elixir:     'elixir',
  erlang:     'erlang',
  groovy:     'groovy',
  pascal:     'pascal',
  fortran:    'fortran',
  cobol:      'cobol',
  vbnet:      'vb',
  ocaml:      'ocaml',
  prolog:     'prolog',
  assembly:   'plaintext',
};
